#cloud-config
# vim: syntax=yaml

groups:
  - docker

users:
  - name: ubuntu
    sudo: ALL=(ALL) NOPASSWD:ALL
    gecos: Default User
    groups: users,admin,wheel,docker
    shell: /bin/bash
    ssh_import_id:
      - gh:pythoninthegrass
  - name: ansible
    sudo: ALL=(ALL) NOPASSWD:ALL
    gecos: Ansible User
    groups: users,admin,wheel
    shell: /bin/bash

ssh_authorized_keys:
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDXjylZLJVRasvFbl3OBM0WFaBspXzhU35GpX3kbCC0PuD8aH9GGJWUpcA4pgimzUXDd/PUIDe9hQSAnikLEk6skm5lhHRLUqqW05srLevYT7vaLi2fplLrn7M1FDUJ8Gz2NatENmZGQho+g1G3CV9UOHhukVP1ULXT/cwWeI2CU5hGQypOZLN8Orymu0rJNwLcadnx/azuHXnfNvZVhKD4ghjiIJfWz++v+rXRTizx5FBPg2MOu1I/7xW5fBjVlBJl3AMdjiCuKWYkEcE5OhYRtexg+pv1lyvYgg0mYSXGJB0ucXjiVPwtVGjo9/LtG6mfYbdhOxTbF5Id4j2tZsA760MC7BYUKgBvc7SxTsNYpoWIdD+T1bx4Qa42Dv3+q0QdBjaGVGEHntAFBSLuKsyBtbylX/d1SzrUZWFJ9+vKzzqdkwKQKSSj+SPQqVL1ablumrU13q5NsuMc33XEsfVp9BYXOJmz9IwMNx6piMhQlBA6VqrmcCZr4i4LlxNhvA0= vmadmin

timezone: America/Chicago

# TODO: QA
# /etc/netplan/50-cloud-init.yaml
network:
  version: 2
  ethernets:
    enp0s2:
      dhcp4: true
      nameservers:
        addresses: [8.8.8.8, 8.8.4.4]

package_update: true
package_upgrade: true
packages: [build-essential, docker.io, net-tools, procps, python3-pip]
# https://github.com/number5/cloud-init/blob/main/doc/examples/cloud-config-apt.txt#L21
apt_get_command: ["apt-get", "--option=Dpkg::Options::=--force-confold", "--option=Dpkg::options::=--force-unsafe-io", "--assume-yes", "--quiet", "--no-install-recommends"]

write_files:
  # * smoke test
  # - path: /etc/systemd/system/container.service
  #   owner: root:root
  #   permissions: '0755'
  #   content: |
  #     [Unit]
  #     Description=Run container
  #     Requires=docker.service
  #     After=docker.service

  #     [Service]
  #     Restart=always
  #     ExecStartPre=-/usr/bin/docker rm container
  #     ExecStart=/usr/bin/docker run --rm --name container hello-world
  #     ExecStop=/usr/bin/docker stop -t 2 container

  - path: /etc/ansible/hosts
    owner: root:root
    permissions: '0644'
    content: |
      [all]
      localhost ansible_connection=local

      [all:vars]
      ansible_user=ansible
      ansible_become=yes
      ansible_become_method=sudo
      ansible_python_interpreter=/usr/bin/python3

runcmd:
  - mkdir -p /home/ubuntu/git
  - git clone https://github.com/pythoninthegrass/ansible-role-hardening.git /home/ubuntu/git/ansible-role-hardening
  - chown -R ubuntu:ubuntu /home/ubuntu/git
  - chmod -R 755 /home/ubuntu/git
  - usermod -aG docker ubuntu
  # * smoke test
  # - systemctl start container
  # - systemctl enable container
  - sudo python3 -m pip install ansible
  - ansible-galaxy collection install community.general
  # * smoke test
  # - ansible all -m ping -i /etc/ansible/hosts
