users:
  - default
  - name: vmadmin
    sudo:  ALL=(ALL) NOPASSWD:ALL
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDXjylZLJVRasvFbl3OBM0WFaBspXzhU35GpX3kbCC0PuD8aH9GGJWUpcA4pgimzUXDd/PUIDe9hQSAnikLEk6skm5lhHRLUqqW05srLevYT7vaLi2fplLrn7M1FDUJ8Gz2NatENmZGQho+g1G3CV9UOHhukVP1ULXT/cwWeI2CU5hGQypOZLN8Orymu0rJNwLcadnx/azuHXnfNvZVhKD4ghjiIJfWz++v+rXRTizx5FBPg2MOu1I/7xW5fBjVlBJl3AMdjiCuKWYkEcE5OhYRtexg+pv1lyvYgg0mYSXGJB0ucXjiVPwtVGjo9/LtG6mfYbdhOxTbF5Id4j2tZsA760MC7BYUKgBvc7SxTsNYpoWIdD+T1bx4Qa42Dv3+q0QdBjaGVGEHntAFBSLuKsyBtbylX/d1SzrUZWFJ9+vKzzqdkwKQKSSj+SPQqVL1ablumrU13q5NsuMc33XEsfVp9BYXOJmz9IwMNx6piMhQlBA6VqrmcCZr4i4LlxNhvA0= vmadmin
