## template: jinja
#cloud-config

# TODO: use jinja to parameterize user data
# jinja user data
# {% if cloudinit.util.get_linux_distro == %}

package_update: true
packages:
  - ansible
  - dnf-plugins-core
  - qemu-guest-agent
  - tree
  - vim

groups:
  - docker

system_info:
  default_user:
    groups: [docker]

# TODO: ^^
users:
  - name: fedora
    plain_text_passwd: 'fedora'
    sudo: [ALL=(ALL) NOPASSWD:ALL]
    chpasswd: { expire: False }
    ssh_pwauth: True
    gecos: Fedora
    home: /home/fedora
    groups: [admin, users, sudo, wheel, docker]
    lock_passwd: true
    shell: /bin/bash
    no_ssh_fingerprints: true
  - name: ansible
    plain_text_passwd: 'ansible'
    sudo: [ALL=(ALL) NOPASSWD:ALL]
    gecos: Ansible
    home: /home/ansible
    groups: [admin, users, sudo, wheel]
    lock_passwd: true
    shell: /bin/bash
    no_ssh_fingerprints: true

# TODO: ^^
runcmd:
  - - systemctl
    - enable
    - '--now'
    - qemu-guest-agent.service
  - dnf config-manager \ --add-repo \ https://download.docker.com/linux/fedora/docker-ce.repo
  - dnf install docker-ce docker-ce-cli containerd.io docker-compose-plugin
  - systemctl enable --now docker
  - su fedora -c "wget -O - https://github.com/pythoninthegrass.keys | sudo tee -a ~/.ssh/authorized_keys"
  - su fedora -c "ssh-keyscan github.com >> ~/.ssh/known_hosts"
  - su fedora -c "mkdir -p /home/fedora/git"
  - su fedora -c "sudo chmod -R 0777 /home/fedora/git"
  - su fedora -c "sudo chown -R fedora:fedora /home/fedora/git"
  # * smoke test
  # - ansible all -m ping -i /etc/ansible/hosts
