---
# Deletes any existing Multipass VM with the supplied name, then creates
# a new VM with the supplied name is created with the supplied parameters.
# Prerequisites:
# A SSH keypair that will be used as one option to log into the new VM must exist.
# A cloud-init configuration file named "cloud-init.yaml" that will be used
# when creating the new VM must exist.
# Variables:
# vmname - Name of the VM that is to be create.
# vmcreationparams - Parameters that will be used when creating the new VM with Multipass.
- name: Log VM creation start
  debug:
    msg: "About to create VM {{ vmname }}..."
- name: Delete existing VM
  shell: |
    multipass info {{ vmname }} > /dev/null 2> /dev/null
    if [ $? -eq 0 ]; then
      multipass delete {{ vmname }}
      multipass purge
    fi
  delegate_to: localhost
- name: Create new VM
  shell: multipass launch --name {{ vmname }} --cloud-init cloud-init.yaml {{ vmcreationparams }}
  delegate_to: localhost
- name: Log VM creation completion
  debug:
    msg: "Finished creating VM {{ vmname }}."
