# code: language=ansible

---
- hosts: localhost
  become: true
  gather_facts: false
  debugger: on_failed
  any_errors_fatal: true
  vars:
    os_environment:
      - key: EDITOR
        value: vim
  pre_tasks:
    - name: Get running ansible user
      ansible.builtin.set_fact:
        local_user: "{{ lookup('env', 'USER') }}"
        cacheable: true
      delegate_to: localhost
    - name: Install git
      ansible.builtin.package:
        name: git
        state: present
    - name: Install redis and python3-redis
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
      loop:
        - redis
        - python3-redis
    - name: Enable redis
      ansible.builtin.service:
        name: redis
        enabled: true
        state: started
    - name: Get OS release
      ansible.builtin.set_fact:
        os_release: "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}"
        major_ver: "{{ ansible_distribution_major_version }}"
        distro: "{{ ansible_distribution }}"
  tasks:
    - name: Setup directory for git repos
      ansible.builtin.file:
        path: "{{ lookup('env', 'HOME') }}/git"
        state: directory
        owner: "{{ local_user }}"
        group: "{{ local_user }}"
        # mode: 01777
        recurse: true

    - name: Install debian dependencies
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
      loop:
        - apt-transport-https
        - bats
        - build-essential
        - ca-certificates
        - cloud-init
        - curl
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - gnupg-agent
        - net-tools
        - python3
        - python3-pip
        - software-properties-common
        - tree
        - vim
      when: ansible_os_family == "Debian"

    - name: Add RPM Fusion Repo
      dnf:
        name: "https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ distro }}.noarch.rpm"
        disable_gpg_check: true
        state: "present"

    - name: Add /etc/yum.repos.d/kubernetes.repo
      ansible.builtin.copy:
        dest: /etc/yum.repos.d/kubernetes.repo
        content: |
          [kubernetes]
          name=Kubernetes
          baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
          enabled=1
          gpgcheck=1
          repo_gpgcheck=1
          gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg
                 https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
        owner: root
        group: root
        mode: 0644
      when: ansible_os_family == "RedHat"

    - name: Install redhat dependencies
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
      loop:
        - bats
        - ca-certificates
        - cloud-init
        - dnf-plugins-core
        - helm
        - kubeadm
        - kubectl
        - python3
      when: ansible_os_family == "RedHat"

    - name: Add docker repo
      ansible.builtin.command: |
        "dnf config-manager --add-repo https://download.docker.com/linux/{{ distro | lower }}/docker-ce.repo"
      when: ansible_os_family == "RedHat"

    - name: Install redhat devtools and libraries
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
      loop:
        - automake
        - containerd.io
        - docker-ce
        - docker-ce-cli
        - docker-compose-plugin
        - gcc
        - gcc-c++
        - kernel-devel
        - make
        - ncurses-devel
        - openssl-devel
        - python3-devel
        - python3-pip
        - python3-psutil
        - python3-setuptools
        - python3-wheel
        - redhat-rpm-config
        - rpm-build
        - rpmdevtools
        - tree
        - vim-enhanced
      when: ansible_os_family == "RedHat"

    - name: Update Packages
      dnf:
        name: "*"
        state: "latest"
